### ISSUE TITLE
use step 3 break: diesel migration run

### ISSUE THREAD

**Issue by JunaYa** [Z4RX/axum_jwt_example#14]
The project is very nice!

![image](https://user-images.githubusercontent.com/13215737/184089802-9182f60e-edb7-415b-a1dc-5022e85dae9e.png)

**Comment by JunaYa** [comment]
It's OK, but I'm not the reason.

**Comment by 3olkin** [comment]
I m glad to hear that you liked this project!
This is the best motivation for me to find time to release a new rethinked version.
