### ISSUE TITLE
[question] how to authenticate a new route?

### ISSUE THREAD

**Issue by silvioprog** [Z4RX/axum_jwt_example#6]
Supposing this new route:

```rust
pub async fn hello() -> &'static str {
    "hello"
}

...

    Router::new()
...
        .route("/hello", get(handlers::hello))
```

the way to make this route "authenticable" is just by adding the parameter `_: User`?:

```
pub async fn hello(_: User) -> &'static str {
    "hello"
}
```

cheers

**Comment by Z4RX** [comment]
yes
`Option<User>` is also supported (I usually add `Option<User>` to graphql)

**Comment by Z4RX** [comment]
Glad to see that my example is useful!
