### ISSUE TITLE
Why Diesel CLI?

### ISSUE THREAD

**Issue by silvioprog** [Z4RX/axum_jwt_example#8]
Just curious, why [Diesel CLI](https://github.com/Z4RX/axum_jwt_example#recommended) instead of [SQLx CLI](https://github.com/launchbadge/sqlx/tree/master/sqlx-cli)? 🤔

**Comment by Z4RX** [comment]
@silvioprog for me there are 2 reasons:
1) I prefer better structured migrations (a bit rails way)
2) diesel cli can be used on heroku
